use sqltcl;
Create Table Class(id int,name varchar(10));
Insert Into Class (id,name)values(1,"Ram"),(2,"Milan"),(3,"Appu"),(4,"Anil");
select * from Class;
Insert Into Info Values (5,"Rina");
commit;
Update Class Set name="Abhiram" Where id="5";
savepoint A;
insert into Class values(6,"Alex");
savepoint B;
select * from Class;
rollback to B;
select * from Class;
rollback to A;
select * from Class;
Delete From Class;
Drop Table Class;